### PR TITLE
use GHAct

### PR DESCRIPTION
**Pull request by nleanba**
~Only merge after https://github.com/factsmission/ghact/pull/3 was merged and published to deno.land/x/, and update the import then~

### CODE REVIEW

**Review by retog — CHANGES_REQUESTED** [review]
Haven't tested it, but it looks good but for the async logging

**Review by retog — APPROVED** [review]
I'd suggest to ger the `postupdate.sparql` to work, rather than removing the file. The SPARQL update is needed to work with taxomplete.

**Comment by nleanba** [comment]
I am pretty sure postupda.sparql (or equivalent) is executed somewhere else -- prefixes are present on both plazi and lindas servers as far as I can tell even though that file was not used in a while.

I have only removed the file because it was unused here.

**Comment by retog** [comment]
> I am pretty sure postupda.sparql (or equivalent) is executed somewhere else -- prefixes are present on both plazi and lindas servers as far as I can tell even though that file was not used in a while.
> 
> I have only removed the file because it was unused here.

It is executed here for plazi endpoint: https://github.com/plazi/ld.plazi.org-config/tree/master/daily-sparql , not sure why we resorted to this horror
For lindas it is in gitlab

**Pull request merged**
